name: dssg2019
channels:
  - conda-forge
dependencies:
  - geopandas
  - geoviews
  - hvplot
  - jupyterlab
  - ipywidgets
  - ipympl
  - ipyleaflet
  - matplotlib
  - nomkl
  - psycopg2
  - sqlalchemy
  - sqlite
