name: dssg2019
channels:
  - conda-forge
dependencies:
  - nomkl
  - pip
  - geopandas=0.5
  - jupyterlab=0.35
  - matplotlib=3.1
  - ipywidgets=7.4
  - ipympl=0.2
  - ipyleaflet=0.10
  - geoviews-core=1.6
  - hvplot=0.4
  - sqlalchemy=1.3
  - sqlite=3.28
